name: Publish Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Configure CI Git User
        run: |
          git config --global user.name '@simonpalepin'
          git config --global user.email 'simonpalepin@users.noreply.github.com'
          git remote set-url origin https://$GITHUB_ACTOR:$ACCESS_TOKEN@github.com/simonpalepin/test-repo
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Checkout and pull branch
        run: git checkout "${GITHUB_REF:11}" && git pull
      - name: Install Packages
        run: yarn install
      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "@test-repo:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish package
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
